//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_cart_movie
    {
        public int iduseraccount { get; set; }
        public long idmovie { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> type { get; set; }
    
        public virtual movie movie { get; set; }
        public virtual net_user net_user { get; set; }
    }
}
