//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebApiDbEntities : DbContext
    {
        public WebApiDbEntities()
            : base("name=WebApiDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<concession> concession { get; set; }
        public virtual DbSet<concession_record> concession_record { get; set; }
        public virtual DbSet<genre> genre { get; set; }
        public virtual DbSet<movie> movie { get; set; }
        public virtual DbSet<movie_admin> movie_admin { get; set; }
        public virtual DbSet<movie_genre> movie_genre { get; set; }
        public virtual DbSet<net_user> net_user { get; set; }
        public virtual DbSet<picture> picture { get; set; }
        public virtual DbSet<shop_cart_movie> shop_cart_movie { get; set; }
        public virtual DbSet<token> token { get; set; }
    }
}
